version: 2

sources:
  - name: exchange_rates
    database: PPNCSRC
    schema: ADMIN
    config:
      freshness:
        warn_after: {count: 7, period: day}
        error_after: {count: 30, period: day}
    tables:
      - name: cv_exchange_rates
        config:
          freshness:
            warn_after: {count: 3, period: day}
            error_after: {count: 7, period: day}
        columns:
          - name: id
            description: Primary key of the exchange rate table
            tests: 
              - unique
              - not_null
          - name: date_val
            description: Date of which the exchange rates are related to.
            tests:
              - unique
              - not_null
            

